/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class honeywell_HoneyWellServe */

#ifndef _Included_honeywell_HoneyWellServe
#define _Included_honeywell_HoneyWellServe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     honeywell_HoneyWellServe
 * Method:    getDeviceId
 * Signature: (Ljava/lang/String;Ljava/lang/String;I[J)V
 */
JNIEXPORT void JNICALL Java_honeywell_HoneyWellServe_getDeviceId
  (JNIEnv *, jobject, jstring, jstring, jint, jlongArray);

/*
 * Class:     honeywell_HoneyWellServe
 * Method:    getDeviceParamterId
 * Signature: (Ljava/lang/String;[JLjava/lang/String;I[J)V
 */
JNIEXPORT void JNICALL Java_honeywell_HoneyWellServe_getDeviceParamterId
  (JNIEnv *, jobject, jstring, jlongArray, jstring, jint, jlongArray);

/*
 * Class:     honeywell_HoneyWellServe
 * Method:    getDeviceValues
 * Signature: (Ljava/lang/String;[J[J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_honeywell_HoneyWellServe_getDeviceValues
  (JNIEnv *, jobject, jstring, jlongArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
