/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class honeywell_JniForC */

#ifndef _Included_honeywell_JniForC
#define _Included_honeywell_JniForC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     honeywell_JniForC
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_honeywell_JniForC_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
